# Generated by Django 5.1.4 on 2024-12-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('area', models.FloatField(verbose_name='Занимаемая площадь (кв. м)')),
            ],
            options={
                'verbose_name': 'Место дислокации',
                'verbose_name_plural': 'Места дислокации',
            },
        ),
        migrations.CreateModel(
            name='TroopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название вида войск')),
            ],
            options={
                'verbose_name': 'Вид войск',
                'verbose_name_plural': 'Виды войск',
            },
        ),
        migrations.CreateModel(
            name='MilitaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер части')),
                ('number_of_platoons', models.PositiveIntegerField(verbose_name='Количество рот')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_units', to='army.location', verbose_name='Место дислокации')),
                ('troop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_units', to='army.trooptype', verbose_name='Вид войск')),
            ],
            options={
                'verbose_name': 'Часть',
                'verbose_name_plural': 'Части',
            },
        ),
        migrations.CreateModel(
            name='Platoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роты')),
                ('number_of_personnel', models.PositiveIntegerField(verbose_name='Количество служащих')),
                ('military_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platoons', to='army.militaryunit', verbose_name='Часть')),
            ],
            options={
                'verbose_name': 'Рота',
                'verbose_name_plural': 'Роты',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('birth_year', models.PositiveIntegerField(verbose_name='Год рождения')),
                ('service_start_year', models.PositiveIntegerField(verbose_name='Год поступления на службу')),
                ('years_of_service', models.PositiveIntegerField(verbose_name='Выслуга лет')),
                ('awards', models.TextField(blank=True, verbose_name='Награды')),
                ('military_events', models.TextField(blank=True, verbose_name='Участие в военных мероприятиях')),
                ('platoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='army.platoon', verbose_name='Рота')),
            ],
            options={
                'verbose_name': 'Личный состав',
                'verbose_name_plural': 'Личный состав',
            },
        ),
    ]
